name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master
  # release:
  #   types: [published]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build artifacts
      run: |
        dotnet tool restore
        dotnet publish Fun.DevTools/Fun.DevTools.fsproj -c Release -o Fun.DevTools.Release --nologo
    

    - name: Change base-tag in index.html
      run: dotnet fsi build.fsx -t ProcessGitHubDocs
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: Create 404.html
      run: cp Fun.DevTools.Release/wwwroot/index.html Fun.DevTools.Release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch Fun.DevTools.Release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        token: ${{ secrets.GH_PAGES_PAT }}
        branch: gh-pages
        folder: Fun.DevTools.Release/wwwroot
        repository-name: slaveOftime/Fun.DevTools.Docs